export const REGISTER = 'REGISTER';
export const REQUEST_REGISTER = 'REQUEST_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN = 'LOGIN';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SET_TOKEN = 'SET_TOKEN';

export const POST_PHOTO = 'POST_PHOTO';
export const REQUEST_POST_PHOTO = 'REQUEST_POST_PHOTO';
export const POST_PHOTO_SUCCESS = 'POST_PHOTO_SUCCESS';
export const POST_PHOTO_FAILURE = 'POST_PHOTO_FAILURE';

export const FETCH_FOLLOW_SUGGESTION_LIST = 'FETCH_FOLLOW_SUGGESTION_LIST';
export const FETCH_FOLLOW_SUGGESTION_LIST_SUCCESS = 'FETCH_FOLLOW_SUGGESTION_LIST_SUCCESS';

export const REQUEST_FOLLOW = 'REQUEST_FOLLOW';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';

export const REQUEST_UNFOLLOW = 'REQUEST_UNFOLLOW';
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';

export const FETCH_TIMELINE_PHOTOS = 'FETCH_TIMELINE_PHOTOS';
export const FETCH_TIMELINE_PHOTOS_SUCCESS = 'FETCH_TIMELINE_PHOTOS_SUCCESS';

export const REQUEST_FETCH_LIKES = 'REQUEST_FETCH_LIKES';
export const FETCH_LIKES_SUCCESS = 'FETCH_LIKES_SUCCESS';

export const REQUEST_LIKE = 'REQUEST_LIKE';
export const LIKE_SUCCESS = 'LIKE_SUCCESS';

export const REQUEST_UNLIKE = 'REQUEST_UNLIKE';
export const UNLIKE_SUCCESS = 'UNLIKE_SUCCESS';

export const REQUEST_FETCH_COMMENTS = 'REQUEST_FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';

export const REQUEST_COMMENT = 'REQUEST_COMMENT';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';

export const REQUEST_AUTHED_USER = 'REQUEST_AUTHED_USER';
export const GET_AUTHED_USER_SUCCESS = 'REQUEST_AUTHED_USER';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
